UpdateChecker: true

#Cooldown between each jump
Cooldown: 0

Velocity: 2
VelcocityUp: 1.5

Sound:
  Enable: true
  Sound: ENTITY_BAT_TAKEOFF
  Volume: 1.0
  Pitch: 1.0

Particles:
  Enable: true
  Particle: CRIT_MAGIC
  Amount: 5

Messages:
  Activated: "&aMultiple jump activated"
  Disabled: "&cMultiple jump disabled"

RemoveFallDamages: true

EnableOnJoin: true

WorldsWhitelist: false

Worlds:
- "world"